name: Command Dispatch

on:
  issue_comment:
    types:
      - created

jobs:
  dispatch_merge_checks:
    name: Merge Checks Requested
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - name: Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          commands: merge-check
          permission: none
          issue-type: pull-request
          token: ${{ secrets.GITHUB_TOKEN }}