name: Integrate

on:
  workflow_dispatch:

jobs:
  integrate:
    name: Integrate
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - run: echo "Hello from Integrate!"