name: Merge Checks

on:
  repository_dispatch:
    types: [merge-check-command]

jobs:
  merge_checks:
    name: Merge Checks
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - name: Update status checks
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{ github.token }}
          context: 'Merge Checks'
          description: 'Merge Checks'
          state: ${{ job.status }}
          sha: ${{ github.event.client_payload.pull_request.head.sha }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Run Merge Checks
        run: |
          echo "Merge checks are starting..."
          echo "Merge checks successful!"
          exit 0

      - name: Update status checks
        uses: Sibz/github-status-action@v1
        if: always()
        with: 
          authToken: ${{ github.token }}
          context: 'Merge Checks'
          description: 'Merge Checks'
          state: ${{ job.status }}
          sha: ${{ github.event.client_payload.pull_request.head.sha }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}