name: Merge Checks

on:
  repository_dispatch:
    types: [merge-check-command]
  workflow_dispatch:

env:
  SHA: ${{ github.event.client_payload.pull_request.head.sha || github.sha }}
  REF: ${{ github.event.client_payload.pull_request.head.ref || github.ref }}

jobs:
  merge_checks:
    name: Merge Checks
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - uses: actions/checkout@v3

      - name: Update status checks
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{ github.token }}
          context: 'Merge Checks'
          description: 'Merge Checks'
          state: ${{ job.status }}
          sha: ${{ env.SHA }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Update comment
        id: comment
        if: github.event_name == 'repository_dispatch'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.client_payload.pull_request.number }}
          body-path: .github/messages/merge_check_processed.md
          reactions: crossed_fingers

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REF }}

      - name: Run Merge Checks
        run: |
          echo "Merge checks are starting..."
          echo "Merge checks successful!"
          exit 0

      - name: Update status checks
        uses: Sibz/github-status-action@v1
        if: always()
        with: 
          authToken: ${{ github.token }}
          context: 'Merge Checks'
          description: 'Merge Checks'
          state: ${{ job.status }}
          sha: ${{ env.SHA }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Update Comment in case of failure
        if: github.event_name == 'repository_dispatch' && (failure() || cancelled())
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          body-path: .github/messages/merge_check_failed.md
          reactions: |
            -1
            confused

      - name: Update Comment in case of failure
        if: github.event_name == 'repository_dispatch' && success()
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          body-path: .github/messages/merge_check_passed.md
          reactions: |
            +1
            hooray