name: Merge

on:
  repository_dispatch:
    types: [merge-command]

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo 'Merge command called!'