name: Merge Checks

on:
  repository_dispatch:
    types: [merge-check-command]
  workflow_dispatch:

env:
  SHA: ${{ github.event.client_payload.pull_request.head.sha || github.sha }}
  REF: ${{ github.event.client_payload.pull_request.head.ref || github.ref }}

jobs:
  merge_checks:
    name: Merge Checks
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - name: Update status checks
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{ github.token }}
          context: 'Merge Checks'
          description: 'Merge Checks'
          state: ${{ job.status }}
          sha: ${{ env.SHA }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Update comment
        if: github.event_name == 'repository_dispatch'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-id: ${{ github.event.client_payload.pull_request.number }}
          body: >-
            In the ballet of code, a Pull Request in hand :woman_dancing:
            Brave the dance, watch your status expand. :crossed_fingers:
            > ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          reactions: crossed_fingers

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REF }}

      - name: Run Merge Checks
        run: |
          echo "Merge checks are starting..."
          echo "Merge checks successful!"
          exit 1

      - name: Update status checks
        uses: Sibz/github-status-action@v1
        if: always()
        with: 
          authToken: ${{ github.token }}
          context: 'Merge Checks'
          description: 'Merge Checks'
          state: ${{ job.status }}
          sha: ${{ env.SHA }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}