name: Merge Check

on:
  workflow_dispatch:

jobs:
  merge:
    name: Merge Checks
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const { GITHUB_SHA, RUN_ID } = process.env;
            github.request('POST /repos/BitGrater/gha-playground/check-runs', {
              name: 'Merge Checks',
              head_sha: `${GITHUB_SHA}`,
              status: 'in_progress',
              details_url: `https://github.com/BitGrater/gha-playground/actions/runs/${RUN_ID}`
            })
        env:
          RUN_ID: ${{ github.run_id }}
      - uses: actions/checkout@v3
      - run: echo $GITHUB_SHA
      - uses: actions/github-script@v6
        with:
          script: |
            const { GITHUB_SHA, RUN_ID } = process.env;
            github.request('POST /repos/BitGrater/gha-playground/check-runs', {
              name: 'Merge Checks',
              head_sha: `${GITHUB_SHA}`,
              status: 'completed',
              conclusion: 'success',
              details_url: `https://github.com/BitGrater/gha-playground/actions/runs/${RUN_ID}`
            })
        env:
          RUN_ID: ${{ github.run_id }}