name: Merge Queue

on:
  merge_group:
    types:
      - "checks_requested"

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello from Merge Queue"
      - run: echo "Hello from the Merge Queue again!"
      - run: exit 1
