name: Merge Queue

on:
  merge_group:

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello from Merge Queue"
      - run: echo ${{ github.event_name }}
      - run: echo "Hello from the Merge Queue again!"
      - run: exit 1
