name: Merge Checks

on:
  repository_dispatch:
    types: [merge-check-command]
  workflow_dispatch:

env:
  SHA: ${{ github.event.client_payload.pull_request.head.sha || github.sha }}
  REF: ${{ github.event.client_payload.pull_request.head.ref || github.ref }}

jobs:
  merge_checks:
    name: Merge Checks
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - name: Update status checks
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{ github.token }}
          context: 'Merge Checks'
          description: 'Merge Checks'
          state: ${{ job.status }}
          sha: ${{ env.SHA }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Update comment
        id: comment
        if: github.event_name == 'repository_dispatch'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.client_payload.pull_request.number }}
          body: >-
            Greetings, brave soul! Your mystical `/merge-check` command has echoed throughout the lands of Middle-Earth! :mage:

            As Gandalf at the Bridge of Khazad-dûm, I stand ready to unleash a storm of **Merge Checks** upon the Pull Request you've masterfully forged. :fire:

            Let's see if this code shall pass, or 'You shall not pass!' will be the lament of our endeavor. :ring:

            Keep a keen eye here for the unfolding tale of success or the need for further journey! :eagle:

            > Merge checks started: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          reactions: crossed_fingers

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REF }}

      - name: Run Merge Checks
        run: |
          echo "Merge checks are starting..."
          echo "Merge checks successful!"
          exit 0

      - name: Update status checks
        uses: Sibz/github-status-action@v1
        if: always()
        with: 
          authToken: ${{ github.token }}
          context: 'Merge Checks'
          description: 'Merge Checks'
          state: ${{ job.status }}
          sha: ${{ env.SHA }}
          target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Update Comment in case of failure
        if: github.event_name == 'repository_dispatch' && (failure() || cancelled())
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          body: >-
            ***

            I bear tidings from our endeavor. :mage:

            Much like the Balrog of Morgoth, your pull request stood defiant in the face of our merge checks. :fire:

            Alas, for now, it seems **'You shall not pass!'** rings true. But fret not! Every hero stumbles, every quest has its trials. :ring:

            Mend your code with the wisdom of the Elves, strength of the Dwarves, and courage of Men and return it to the anvil! :hammer:

            We shall overcome this, together. Onwards to victory, for not all those who wander are lost! :eagle:"

            > Verdict: :stop_sign: **FAILED** :stop_sign:
          reactions: |
            -1
            confused

      - name: Update Comment in case of failure
        if: github.event_name == 'repository_dispatch' && success()
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          body: >-
            ***

            I bring good news from the realms of Middle-Earth! :mage:

            Like Frodo and Sam's victorious journey to Mount Doom, your pull request has braved the fiery depths of our merge checks. :fire:
  
            And behold, 'You shall pass!' rings loud and clear! :ring:

            Your code, now tried and true, stands ready to join the develop branch in the legendary halls of the repository.

            Celebrate this triumph! For even the smallest pull request can change the course of the future. :eagle:

            Let the eagles soar and the trumpets sound in your honor! Onward to the next great quest!

            > Verdict: :heavy_check_mark: **SUCCESS** :heavy_check_mark:
          reactions: |
            +1
            hooray