name: Merge Check

on:
  repository_dispatch:
    types: [merge-command]

jobs:
  merge:
    name: Merge Checks
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Update Status
        uses: actions/github-script@v6
        with:
          script: |
            const { RUN_ID } = process.env;
            const commit_sha = context.payload.client_payload.pull_request.head_sha;
            console.log(commit_sha)
            github.request('POST /repos/BitGrater/gha-playground/check-runs', {
              name: 'Merge Checks',
              head_sha: commit_sha,
              status: 'in_progress',
              details_url: `https://github.com/BitGrater/gha-playground/actions/runs/${RUN_ID}`
            });
        env:
          RUN_ID: ${{ github.run_id }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.pull_request.head_sha }}

      - run: echo 'Merge command called!'
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload.client_payload.pull_request.head.sha)

            - name: Update Status
            uses: actions/github-script@v6
            with:
              script: |
                const { RUN_ID } = process.env;
                const commit_sha = context.payload.client_payload.pull_request.head_sha;
                github.request('POST /repos/BitGrater/gha-playground/check-runs', {
                  name: 'Merge Checks',
                  head_sha: commit_sha,
                  status: 'completed',
                  conclusion: 'success',
                  details_url: `https://github.com/BitGrater/gha-playground/actions/runs/${RUN_ID}`
                });
            env:
              RUN_ID: ${{ github.run_id }}
