name: PR

on:
  pull_request:

jobs:
  pr_checks:
    name: PR Checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "Example PR Check - automatically triggered"