name: PR

on:
  pull_request:

jobs:
  pr_checks:
    name: PR Checks
    runs-on: ubuntu-22.04
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - run: echo "$GITHUB_SHA"
      - uses: actions/github-script@v6
        with:
          script: |
            const { GITHUB_SHA } = process.env
            console.log({ github, context })
            github.request('POST /repos/BitGrater/gha-playground/check-runs', {
              name: 'Merge',
              head_sha: GITHUB_SHA,
              status: 'completed',
              conclusion: 'success'
            })